#pragma once

#include "sdk/classes/crc/crc.hpp"
#include "sdk/math/base.hpp"
#include "sdk/classes/md5/md5.hpp"
#include "sdk/classes/Recv/client_class.hpp"
#include "sdk/classes/Recv/recv.hpp"
#include "sdk/classes/BSPFlags.hpp"
#include "sdk/classes/CGlobalVarsBase.hpp"
#include "sdk/classes/CGlowObject.hpp"
#include "sdk/classes/CHandle.hpp"
#include "sdk/classes/CInput.hpp"
#include "sdk/classes/CUtlMemory.hpp"
#include "sdk/classes/CUtlVector.hpp"
#include "sdk/classes/KeyValues.hpp"
#include "sdk/classes/PlayerInfo.hpp"
#include "sdk/classes/CClientState.hpp"
#include "sdk/classes/bf_read.hpp"
#include "sdk/classes/DataMap.hpp"
#include "sdk/classes/CCSGOPlayerAnimState.hpp"

#include "sdk/interfaces/IAppSystem.hpp"
#include "sdk/interfaces/IBaseClientDLL.hpp"
#include "sdk/interfaces/IClientEntity.hpp"
#include "sdk/interfaces/ICollideable.hpp"
#include "sdk/interfaces/IClientEntityList.hpp"
#include "sdk/interfaces/IVEngineClient.hpp"