name: herby

on: [pull_request, push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: MSBuild
      run: msbuild herby.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m
    - name: SHA1 
      working-directory: Release
      run: sha1sum herby.dll > herby.dll.sha1
      
    - uses: actions/upload-artifact@v1
      with:
        name: herby
        path: Release
